%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: D:\NTU_ML_basic\gasprices.csv
%
% Auto-generated by MATLAB on 13-Jul-2023 14:28:46

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = [6, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["AverageAnnualGasolinePetrolRetailPricesInSelectedCountriesUSPer", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
gasprices = readtable("D:\NTU_ML_basic\gasprices.csv", opts);


%% Clear temporary variables
clear opts